
GetObjects
提示用户选取一个或多个物件。
语法
rhinoscriptsyntax.GetObjects ( message=None, filter=0, group=True, preselect=False, select=False, objects=None, minimum_count=1, maximum_count=0, custom_filter=None )
rhinoscript.selection.GetObjects ( message=None, filter=0, group=True, preselect=False, select=False, objects=None, minimum_count=1, maximum_count=0, custom_filter=None )
参数




message
可选参数。字符串。提示信息。


filter
可选参数。数字。可以选取的物件类型（点，曲线，曲面，网格等）。类型代码可以相加代入此参数，以实现多种类型物件的选取。





值
值（十六进制）
描述


0
0x0
所有物件（默认值）


1
0x1
点


2
0x2
点云


4
0x4
曲线


8
0x8
曲面或单一曲面 Brep


16
0x10
多重曲面或多个面


32
0x20
网格


256
0x100
灯光


512
0x200
注释


4096
0x1000
图块实例


8192
0x2000
注释点物件


16384
0x4000
操作点物件


32768
0x8000
子视图


65536
0x10000
填充图案


131072
0x20000
变形控制


134217728
0x8000000
变形控制器


268435456
0x10000000
Phantom


536870912
0x20000000
截平面


1073741824
0x40000000
挤出物




group
可选参数。布尔值。群组选取。如果省略此参数，用户选取一个群组中的物件，整个群组都会被选取 (True)。注意，如果 filter参数不为 0 （所有物件），群组选取失效。


preselect
可选参数。布尔值。允许直接使用执行函数之前选取的物件。如果省略，将不会使用之前选取的物件（False）。


select
可选参数。布尔值。函数执行结束以后选取的物件是否为选中状态。如果省略，函数执行之前选取的物件依旧为选中状态，之后选取的物件依旧为非选中状态。


objects
可选参数。列表。允许选取物件的 Guid 构成的列表。


minimum_count
可选参数。数字。最小选取数量。如果省略，至少选取一个(1)物件。


maximum_count
可选参数。数字。最大选取数量。如果为 0 （默认值），用户必须按回车键以完成选取。如果为 -1 选取数量达到最小选取数量时完成选取。如果大于 0 ，达到最大选取数量时完成选取。如果在视图中框选物件的数量大于最大选取数量，这种框选将被忽略。


custom_filter
可选参数。传递 Rhino 物件、几何体、元素序号给函数，返回 True 或 False 表明物件是否能被选取。


返回值




列表
由选取的物件 Guid 构成的列表。


示例
import rhinoscriptsyntax as rs
objectIds = rs.GetObjects("Pick some curves", rs.filter.curve)
for id in objectIds: print "Object identifier:", id
同见
GetCurveObject
GetObject
GetSurfaceObject
