
GetObject
提示用户选取一个物件。
语法
rhinoscriptsyntax.GetObject ( message=None, filter=0, preselect=False, select=False, custom_filter=None, subobjects=False)
rhinoscript.selection.GetObject ( message=None, filter=0, preselect=False, select=False, custom_filter=None, subobjects=False)
参数




message
可选参数。字符串。提示信息。


filter
可选参数。数字。可以选取的物件类型（点，曲线，曲面，网格等）。类型代码可以相加代入此参数，以实现多种类型物件的选取。




值
描述


0
所有物件（默认值）


1
点


2
点云


4
曲线


8
曲面或单一曲面 Brep


16
多重曲面或多个面


32
网格


256
灯光


512
注释


4096
图块实例


8192
注释点物件


16384
操作点物件


32768
子视图


65536
填充图案


131072
变形控制


134217728
变形控制器


268435456
Phantom


536870912
截平面




preselect
可选参数。布尔值。允许直接使用执行函数之前选取的物件。如果省略，将不会使用之前选取的物件（False）。


select
可选参数。布尔值。函数执行结束以后选取的物件是否为选中状态。如果省略，函数执行之前选取的物件依旧为选中状态，之后选取的物件依旧为非选中状态。


subobjects
可选参数。布尔值。允许副物件选取。如果为 True ，将使用 ObjRef 类替代 ID 。这个类可以传递到其他函数。


返回值




Guid
执行成功，返回选取物件的ID。


None
没有选取物件。


示例
import rhinoscriptsyntax as rs
objectId = rs.GetObject("Pick any object")
if objectId:
    print "Object identifier:", objectId
 
objectId = rs.GetObject("Pick a curve or surface", rs.filter.curve | rs.filter.surface)
if objectId:
    print "Object identifier:", objectId
 
同见
GetCurveObject
GetObjectEx
GetObjects
GetSurfaceObject
