
CircleCenterPoint
返回圆的中心点。
语法
rhinoscriptsyntax.CircleCenterPoint (curve_id, segment_index=-1, return_plane=False)
rhinoscript.curve.CircleCenterPoint (curve_id, segment_index=-1, return_plane=False)
参数




curve_id
必须参数。代表曲线标识符的符串或 Guid


segment_index
可选参数。数字。如果 curve_id 标示出一个多重曲线物件，那么 segment_index 标示要计算的是多重曲线的哪一段。


return_plane
可选参数。布尔值。如果为 True , 将返回圆所在的平面替代中点。


返回值




Point3d
如果执行成功，返回作为圆中心点的 3-D 点。


Plane
参数 return_plane 为 True 且执行成功，返回圆的平面。


None
如果执行不成功或出错，返回空值。


示例
import rhinoscriptsyntax as rs
id = rs.GetObject("Select circle")
if rs.IsCircle(id):
    point = rs.CircleCenterPoint(id)
    rs.AddPoint( point )
同见
AddCircle
AddCircle3Pt
CircleCircumference
CircleRadius
IsCircle
 
 
