
DivideCurveEquidistant
按直线距离的等分点划分曲线。
不同于 DivideCurve 函数和 DivideCurveLength函数是按照弧长等分曲线，或是沿曲线找到距离相等的两个点，这个函数是按照点之间的直线距离分段曲线的。
语法
rhinoscriptsyntax.DivideCurveEquidistant (curve_id, distance, create_points=False, return_points=True)
rhinoscript.curve.DivideCurveEquidistant (curve_id, distance, create_points=False, return_points=True)
参数




curve_id
必须参数。字符串或 Guid。物件的 ID 。


distance
必须参数。数字。分段点之间的直线距离。


create_points
可选参数。布尔值。创建分段点。如果省略或为 False，将不会创建点。


return_points
可选参数。布尔值。返回一组 3-D 点。如果省略或为 True，将返回点。如果为 False，将返回一组曲线参数。


返回值




List.
如果省略 return_points 参数或设为 True，返回包含 3-D 分段点的列表。


List.
如果 return_points 参数设为 False，返回包含分段位置参数的列表。


None
如果执行不成功或出错，返回空值。


示例
import rhinoscriptsyntax as rs
obj = rs.GetObject("Select a curve", rs.filter.curve)
if obj:
    points = rs.DivideCurveEquidistant(obj, 4, True)
同见
DivideCurve
DivideCurveLength
