
ExtendCurve
通过直线、圆弧或顺滑的过渡，延伸一个未闭合的曲线物件直到其与选中的物件相交。
语法
rhinoscriptsyntax.ExtendCurve (curve_id, extension_type, side, boundary_object_ids)
rhinoscript.curve.ExtendCurve (curve_id, extension_type, side, boundary_object_ids)
参数




curve_id
必须参数。字符串或 Guid。物件的 ID 。


extension_type
必须参数。数字。延伸的类型。




值
描述


0
直线 - 创建一个与原始曲线相切的直线延伸。


1
圆弧 - 创建一个与原始曲线相切的圆弧延伸。


2
顺滑 - 创建一个与原始曲线曲率连续光滑曲线。




side
必须参数。数字。延伸方向。




值
描述


0
从曲线起点开始延伸。


1
从曲线终点开始延伸。




boundary_object_ids
必须参数。列表或元组。作为边界的曲线、曲面和多重曲面物件的 ID。


返回值




Guid
执行成功，返回延伸物件的ID。


None
如果执行不成功或出错，返回空值。


示例
import rhinoscriptsyntax as rs
filter = rs.filter.curve | rs.filter.surface | rs.filter.polysurface
objects = rs.GetObjects("Select boundary objects", filter)
if objects:
    curve = rs.GetObject("Select curve to extend", rs.filter.curve)
    if curve: rs.ExtendCurve( curve, 2, 1, objects )
同见
ExtendCurveLength
ExtendCurvePoint
