
IsPointOnCurve
判断一个点是否在曲线上。
语法
rhinoscriptsyntax.IsPointOnCurve (object_id, point, segment_index=-1)
rhinoscript.curve.IsPointOnCurve (object_id, point, segment_index=-1)
参数




object_id
必须参数。字符串或 Guid。物件的 ID 。


point
必须参数。包含三个数字的列表或者 Point3d 对象。要计算的点或采样点。


segment_index
可选参数。数字。如果 object_id 标示出一个多重曲线物件，那么 segment_index 标示要计算的是多重曲线的哪一段。


返回值




布尔值
如果执行成功，返回 True，如果执行不成功返回 False。


示例
import rhinoscriptsyntax as rs
obj = rs.GetObject("Select a curve")
if rs.IsCurve(obj):
    point = rs.GetPoint("Pick a test point")
    if point:
        if rs.IsPointOnCurve(obj, point):
            print "The point is on the curve"
        else:
            print "The point is not on the curve"
同见
IsCurve
 
