
ScaleObject
缩放一个单一物件。此函数可以用于均匀缩放或非均匀缩放。缩放基于当前的构造平面。
语法
rhinoscriptsyntax.ScaleObject (object_id, origin, scale, copy=False)
rhinoscript.object.ScaleObject (object_id, origin, scale, copy=False)
参数




object_id
必须参数。字符串或 Guid。要缩放物件的 ID 。


origin
必须参数。Point3d 点。缩放原点。


scale
必须参数。列表。由 X、Y、Z 三个轴的缩放因子构成的列表。缩放基于当前的构造平面。


copy
可选参数。布尔值。复制物件。如果省略，执行过程中不复制物件（False）。


返回值




Guid
执行成功，返回缩放后物件的ID。


示例
import rhinoscriptsyntax as rs
obj = rs.GetObject("Select object to scale")
if obj:
    origin = rs.GetPoint("Origin point")
    if origin:
        rs.ScaleObject( obj, origin, (1,2,3), True )
同见
ScaleObjects
