
GetRectangle
暂停并等待用户输入一个矩形。
语法
rhinoscriptsyntax.GetRectangle (mode=0, base_point=None, prompt1=None, prompt2=None, prompt3=None)
rhinoscript.userinterface.GetRectangle (mode=0, base_point=None, prompt1=None, prompt2=None, prompt3=None)
参数




mode
可选参数。数字。矩形选取模式。如果未指定，所有模式都可用（0）。矩形选取模式如下：




值
描述


0
所有模式。


1
角点。选取两个角点创建矩形。


2
三点。选取三个点创建矩形。


3
垂直。选取三个点创建垂直矩形。


4
中心。通过选取中心点及一个角点来创建矩形。




base_point
可选参数。三个数字构成的列表或 Point3d 点对象。一个 3-D 基点。


prompt1
可选参数。字符串。第一条提示信息。


prompt2
可选参数。字符串。第二条提示信息。


prompt3
可选参数。字符串。第三条提示信息。只有使用“三点”和“垂直”模式时第三条提示信息才起作用。


返回值




元组
作为矩形角点的四个 3-D 点构成的元组。返回的点是按逆时针排序的。请参考下方的图示。


None
如果执行不成功或出错，返回空值。


示例
import rhinoscriptsyntax as rs
rect = rs.GetRectangle()
if rect:
    for i, corner in enumerate(rect):
        rs.AddTextDot( i, corner )
 

同见
GetPoint
GetPoints
 
