
AddSrfControlPtGrid
通过网状排布的控制点创建一个曲面。
语法
rhinoscriptsyntax.AddSrfControlPtGrid (count, points, degree=(3,3))
rhinoscript.surface.AddSrfControlPtGrid (count, points, degree=(3,3))
参数




count
必须参数。两个数构成的元组。U 方向和 V 方向的控制点数量。


points
必须参数。列表或元组。作为控制点的 3-D 点。


degree
可选参数。两个数构成的元组。曲面在 U 方向和 V 方向的阶数。如果省略，新曲面 U 方向和 V 方向的阶数都将设置为 3 。


返回值




Guid
执行成功，返回新物件的ID。


None
如果执行不成功或出错，返回空值。


示例
import rhinoscriptsyntax as rs
count = (5,5)
points = []
for i in range(count[0]):
    for j in range(count[1]):
        points.append( (i*2, j*4, j%3) )
rs.AddSrfControlPtGrid( count, points )
同见
AddEdgeSrf
AddSrfPt
AddSrfPtGrid
 
