
FilletSurfaces
在两个曲面之间创建连续的圆角。注意，此函数不会在圆角处剪切原始曲面。
语法
rhinoscriptsyntax.FilletSurfaces (surface0, surface1, radius, uvparam0=None, uvparam1=None)
rhinoscript.surface.FilletSurfaces (surface0, surface1, radius, uvparam0=None, uvparam1=None)
参数




surface0
必须参数。字符串。第一个曲面物件 ID。


surface1
必须参数。字符串。第二个曲面物件 ID。


radius
必须参数。数字。正值圆角半径。


uvparam0
可选参数。两个数构成的元组。靠近 surface0 要倒圆角位置的曲面 UV 参数。


uvparam1
可选参数。两个数构成的元组。靠近 surface1 要倒圆角位置的曲面 UV 参数。


返回值




列表
创建曲面物件的 ID 。


None
如果执行不成功或出错，返回空值。


备注
  参数 uvparam0 和参数 uvparam1 决定了偏移方向。曲面将会向 surface0(uvparam0) 到 surface1(uvparam1) 中间的部分偏移。
示例
import rhinoscriptsyntax as rs
surface0 = rs.GetObject("First surface", rs.filter.surface)
surface1 = rs.GetObject("Second surface", rs.filter.surface)
rs.FilletSurfaces(surface0, surface1, 2.0)
同见
IsSurface
 
