
PullCurve
拉回一个曲线物件到一个曲面物件。获取更多相关信息，请参考 Rhino 帮助文件中有关Pull 指令的部分。
语法
rhinoscriptsyntax.PullCurve(surface, curve, delete_input=False)
rhinoscript.surface.PullCurve(surface, curve, delete_input=False)
参数




surface
必须参数。字符串或 Guid。要拉回的目标曲面的ID。


curve
必须参数。字符串或 Guid。要拉回的曲线物件 ID 。


delete_input
可选参数。布尔值。删除输入曲线。如果省略，输入曲线不会被删除（False）。


返回值




列表
执行成功，返回新曲线物件的 ID 。


None
如果执行不成功或出错，返回空值。


示例
import rhinoscriptsyntax as rs
curve = rs.GetObject("Select curve to pull", rs.filter.curve )
surface = rs.GetObject("Select surface that pulls", rs.filter.surface )
rs.PullCurve(surface, curve)
同见
IsSurface
 
